service:
  name: dcs-poc
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

stage: dev
region: ap-south-1

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  dcs:
    handler: handler.dcs
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
